version: 0.0.0.{build}
skip_tags: true
environment:
  ZIP: C:\Program Files\7-Zip
  QTDIR: C:\Qt\5.6\mingw53_32\bin
  EDITOR_OUTPUT_PATH: c:\leveleditor
  QTMINGW: C:\Qt\Tools\mingw530_32\bin
  NSIS: C:\Program Files (x86)\NSIS
  PYTHON: C:\Python34
build_script:
- cmd: >-
    set PATH=%QTDIR%;%MINGW%;%ZIP%

    cd src

    qmake leveleditor.pro

    mingw32-make -j16

    md dist

    copy release\*.exe .\dist

    cd dist

    @echo Coping qt dependency libraries...

    windeployqt --no-opengl-sw --no-system-d3d-compiler leveleditor.exe

    7z a leveleditor.7z *

    cd ..

    cd ..
test_script:
- cmd: >-
    set PATH=%QTDIR%;%MINGW%

    cd test/unittest

    qmake unittest.pro

    mingw32-make -j16

    rem release\unittest_leveleditor.exe
artifacts:
- path: src\dist\leveleditor.7z
  name: demo
deploy:
- provider: GitHub
  auth_token:
    secure: D/3LJCvnQzb2LT6rtq7KCPZcyW4fCmh9S0zJw4jsxGLRLSPRMaIdmd2iw/Yri+vT
  artifact: /leveleditor.*\.(exe|7z|zip)/
  draft: false
  on:
    appveyor_repo_tag: true
notifications:
- provider: Email
  to:
  - wazcd_1608@qq.com
  - 975098440@qq.com
  - 1161294726@qq.com
  - 184773349@qq.com
  subject: Build status of leveleditor
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false