HEADERS += \
    $$PWD/tst_mainwindow.h \
    $$PWD/component/tst_basedock.h \
    $$PWD/component/tst_centralwidget.h \
    $$PWD/component/characterdock/tst_characterdock.h \
    $$PWD/component/characterdock/tst_characterview.h \
    $$PWD/component/layerdock/tst_boldcurrentitemdelegate.h \
    $$PWD/component/layerdock/tst_iconcheckdelegate.h \
    $$PWD/component/layerdock/tst_layerdock.h \
    $$PWD/component/layerdock/tst_layerview.h \
    $$PWD/component/mapsdock/tst_mapsdock.h \
    $$PWD/component/mapsdock/tst_mapsproxyview.h \
    $$PWD/component/mapsdock/tst_modstab.h \
    $$PWD/component/mapsdock/tst_modstree.h \
    $$PWD/component/mapsdock/modstab/tst_mapstab.h \
    $$PWD/component/mapsdock/modstab/tst_mapview.h \
    $$PWD/component/miniscenedock/tst_miniscenedock.h \
    $$PWD/component/miniscenedock/tst_minisceneframe.h \
    $$PWD/component/otherdock/tst_sounddock.h \
    $$PWD/component/propertydock/tst_propertiesdock.h \
    $$PWD/component/propertydock/tst_propertybrowser.h \
    $$PWD/component/propertydock/tst_varianteditorfactory.h \
    $$PWD/component/propertydock/tst_variantpropertymanager.h \
    $$PWD/component/propertydock/widget/tst_filepathedit.h \
    $$PWD/component/propertydock/widget/tst_pixmapedit.h \
    $$PWD/component/propertydock/widget/tst_plaintexteditor.h \
    $$PWD/component/propertydock/widget/tst_sounditemedit.h \
    $$PWD/component/propertydock/widget/tst_sounditemsourceedit.h \
    $$PWD/component/propertydock/widget/tst_soundsetedit.h \
    $$PWD/component/propertydock/widget/tst_stringexedit.h \
    $$PWD/component/tabwidget/tst_graphicsview.h \
    $$PWD/component/tabwidget/tst_graphicsviewcontexmenu.h \
    $$PWD/component/tabwidget/tst_tabcontainer.h \
    $$PWD/component/tabwidget/tst_tabwidget.h \
    $$PWD/component/tilesetdock/tst_tilesetdock.h \
    $$PWD/component/tilesetdock/tst_tilesettab.h \
    $$PWD/component/tilesetdock/tst_tilesetview.h \
    $$PWD/component/undodock/tst_undodock.h \
    $$PWD/dialogs/tst_aboutdialog.h \
    $$PWD/dialogs/tst_abstractdialog.h \
    $$PWD/dialogs/tst_exceptiondialog.h \
    $$PWD/dialogs/tst_loadingdialog.h \
    $$PWD/dialogs/tst_newmapdialog.h \
    $$PWD/dialogs/tst_preferencesdialog.h \
    $$PWD/dialogs/tst_selectrootdialog.h \
    $$PWD/dialogs/tst_soundresourcedialog.h \
    $$PWD/dialogs/tst_soundresourceset.h \
    $$PWD/dialogs/preferencesdialog/module/tst_languagemanager.h \
    $$PWD/dialogs/preferencesdialog/module/tst_shortkeymanager.h \
    $$PWD/style/tst_proxystyle.h \
    $$PWD/style/tst_stylehelper.h \
    $$PWD/widgets/tst_flexiblescrollbar.h \
    $$PWD/widgets/tst_keycodeedit.h \
    $$PWD/widgets/tst_shortcutview.h \
    $$PWD/widgets/tst_zoomcombobox.h

SOURCES += \
    $$PWD/tst_mainwindow.cpp \
    $$PWD/component/tst_basedock.cpp \
    $$PWD/component/tst_centralwidget.cpp \
    $$PWD/component/characterdock/tst_characterdock.cpp \
    $$PWD/component/characterdock/tst_characterview.cpp \
    $$PWD/component/layerdock/tst_boldcurrentitemdelegate.cpp \
    $$PWD/component/layerdock/tst_iconcheckdelegate.cpp \
    $$PWD/component/layerdock/tst_layerdock.cpp \
    $$PWD/component/layerdock/tst_layerview.cpp \
    $$PWD/component/mapsdock/tst_mapsdock.cpp \
    $$PWD/component/mapsdock/tst_mapsproxyview.cpp \
    $$PWD/component/mapsdock/tst_modstab.cpp \
    $$PWD/component/mapsdock/tst_modstree.cpp \
    $$PWD/component/mapsdock/modstab/tst_mapstab.cpp \
    $$PWD/component/mapsdock/modstab/tst_mapview.cpp \
    $$PWD/component/miniscenedock/tst_miniscenedock.cpp \
    $$PWD/component/miniscenedock/tst_minisceneframe.cpp \
    $$PWD/component/otherdock/tst_sounddock.cpp \
    $$PWD/component/propertydock/tst_propertiesdock.cpp \
    $$PWD/component/propertydock/tst_propertybrowser.cpp \
    $$PWD/component/propertydock/tst_varianteditorfactory.cpp \
    $$PWD/component/propertydock/tst_variantpropertymanager.cpp \
    $$PWD/component/propertydock/widget/tst_filepathedit.cpp \
    $$PWD/component/propertydock/widget/tst_pixmapedit.cpp \
    $$PWD/component/propertydock/widget/tst_plaintexteditor.cpp \
    $$PWD/component/propertydock/widget/tst_sounditemedit.cpp \
    $$PWD/component/propertydock/widget/tst_sounditemsourceedit.cpp \
    $$PWD/component/propertydock/widget/tst_soundsetedit.cpp \
    $$PWD/component/propertydock/widget/tst_stringexedit.cpp \
    $$PWD/component/tabwidget/tst_graphicsview.cpp \
    $$PWD/component/tabwidget/tst_graphicsviewcontexmenu.cpp \
    $$PWD/component/tabwidget/tst_tabcontainer.cpp \
    $$PWD/component/tabwidget/tst_tabwidget.cpp \
    $$PWD/component/tilesetdock/tst_tilesetdock.cpp \
    $$PWD/component/tilesetdock/tst_tilesettab.cpp \
    $$PWD/component/tilesetdock/tst_tilesetview.cpp \
    $$PWD/component/undodock/tst_undodock.cpp \
    $$PWD/dialogs/tst_aboutdialog.cpp \
    $$PWD/dialogs/tst_abstractdialog.cpp \
    $$PWD/dialogs/tst_exceptiondialog.cpp \
    $$PWD/dialogs/tst_loadingdialog.cpp \
    $$PWD/dialogs/tst_newmapdialog.cpp \
    $$PWD/dialogs/tst_preferencesdialog.cpp \
    $$PWD/dialogs/tst_selectrootdialog.cpp \
    $$PWD/dialogs/tst_soundresourcedialog.cpp \
    $$PWD/dialogs/tst_soundresourceset.cpp \
    $$PWD/dialogs/preferencesdialog/module/tst_languagemanager.cpp \
    $$PWD/dialogs/preferencesdialog/module/tst_shortkeymanager.cpp \
    $$PWD/style/tst_proxystyle.cpp \
    $$PWD/style/tst_stylehelper.cpp \
    $$PWD/widgets/tst_flexiblescrollbar.cpp \
    $$PWD/widgets/tst_keycodeedit.cpp \
    $$PWD/widgets/tst_shortcutview.cpp \
    $$PWD/widgets/tst_zoomcombobox.cpp
