HEADERS += \
    $$PWD/tst_core.h \
    $$PWD/assets/tst_assetsmanager.h \
    $$PWD/assets/tst_cachedpixmap.h \
    $$PWD/assets/tst_cachedsound.h \
    $$PWD/assets/tst_faceid.h \
    $$PWD/assets/tst_map.h \
    $$PWD/assets/tst_mapbundle.h \
    $$PWD/assets/tst_module.h \
    $$PWD/assets/tst_pixmap.h \
    $$PWD/assets/tst_sound.h \
    $$PWD/assets/tst_tileid.h \
    $$PWD/assets/tst_tileset.h \
    $$PWD/document/tst_document.h \
    $$PWD/document/graphics/tst_graphicsscene.h \
    $$PWD/document/graphics/tst_sceneitem.h \
    $$PWD/document/graphics/layeritem/tst_areaslayeritem.h \
    $$PWD/document/graphics/layeritem/tst_boxlayeritem.h \
    $$PWD/document/graphics/layeritem/tst_darealayeritem.h \
    $$PWD/document/graphics/layeritem/tst_layeritem.h \
    $$PWD/document/graphics/layeritem/tst_objectlayeritem.h \
    $$PWD/document/graphics/layeritem/tst_platlayeritem.h \
    $$PWD/document/graphics/layeritem/tst_tilelayeritem.h \
    $$PWD/document/graphics/layeritem/tst_walllayeritem.h \
    $$PWD/document/graphics/layeritem/objectitem/tst_areaitem.h \
    $$PWD/document/graphics/layeritem/objectitem/tst_boxitem.h \
    $$PWD/document/graphics/layeritem/objectitem/tst_dareaitem.h \
    $$PWD/document/graphics/layeritem/objectitem/tst_objectitem.h \
    $$PWD/document/graphics/layeritem/objectitem/tst_platitem.h \
    $$PWD/document/graphics/layeritem/objectitem/tst_tileitem.h \
    $$PWD/document/graphics/layeritem/objectitem/tst_wallitem.h \
    $$PWD/document/graphics/layeritem/objectitem/tileitem/tst_dooritem.h \
    $$PWD/document/graphics/layeritem/objectitem/tileitem/tst_randomregionitem.h \
    $$PWD/document/graphics/layeritem/objectitem/tileitem/tst_startpointitem.h \
    $$PWD/document/graphics/layeritem/objectitem/tileitem/tst_trackitem.h \
    $$PWD/document/graphics/tools/tst_abstracttool.h \
    $$PWD/document/graphics/uiitem/tst_darkmaskitem.h \
    $$PWD/document/graphics/uiitem/tst_hovereditem.h \
    $$PWD/document/graphics/uiitem/tst_mousetraceitem.h \
    $$PWD/document/graphics/uiitem/tst_objectareaitem.h \
    $$PWD/document/graphics/uiitem/tst_selecteditem.h \
    $$PWD/document/graphics/uiitem/tst_selecteditems.h \
    $$PWD/document/graphics/uiitem/tst_selectionrectangle.h \
    $$PWD/document/graphics/uiitem/tst_tilestampitem.h \
    $$PWD/document/graphics/uiitem/tst_uiitemsgroup.h \
    $$PWD/document/model/tst_animationsmodel.h \
    $$PWD/document/model/tst_areasmodel.h \
    $$PWD/document/model/tst_basemodel.h \
    $$PWD/document/model/tst_boxesmodel.h \
    $$PWD/document/model/tst_dareasmodel.h \
    $$PWD/document/model/tst_enemyfactorymodel.h \
    $$PWD/document/model/tst_eventsmodel.h \
    $$PWD/document/model/tst_platformsmodel.h \
    $$PWD/document/model/tst_respawnsmodel.h \
    $$PWD/document/model/tst_scenemodel.h \
    $$PWD/document/model/tst_tilelayermodel.h \
    $$PWD/document/model/tst_triggersmodel.h \
    $$PWD/document/model/tst_wallsmodel.h \
    $$PWD/document/model/entity/tst_animation.h \
    $$PWD/document/model/entity/tst_area.h \
    $$PWD/document/model/entity/tst_box.h \
    $$PWD/document/model/entity/tst_darea.h \
    $$PWD/document/model/entity/tst_door.h \
    $$PWD/document/model/entity/tst_enemy.h \
    $$PWD/document/model/entity/tst_enemyfactory.h \
    $$PWD/document/model/entity/tst_frame.h \
    $$PWD/document/model/entity/tst_object.h \
    $$PWD/document/model/entity/tst_plat.h \
    $$PWD/document/model/entity/tst_point.h \
    $$PWD/document/model/entity/tst_pointf.h \
    $$PWD/document/model/entity/tst_rect.h \
    $$PWD/document/model/entity/tst_respawn.h \
    $$PWD/document/model/entity/tst_startpoint.h \
    $$PWD/document/model/entity/tst_tile.h \
    $$PWD/document/model/entity/tst_tilemovemodel.h \
    $$PWD/document/model/entity/tst_trigger.h \
    $$PWD/document/model/entity/tst_wall.h \
    $$PWD/document/property/tst_propertyitem.h \
    $$PWD/document/property/tst_propertyobject.h \
    $$PWD/document/property/tst_propertysheet.h \
    $$PWD/document/undocommand/tst_objectaddcommand.h \
    $$PWD/document/undocommand/tst_objectundocommand.h \
    $$PWD/document/undocommand/tst_propertyundocommand.h \
    $$PWD/document/undocommand/tst_removeselectioncommand.h \
    $$PWD/model/tst_charactermodel.h \
    $$PWD/model/tst_mapsmodel.h \
    $$PWD/model/tst_tilesetmodel.h \
    $$PWD/model/tst_tilesetmodelmanager.h \
    $$PWD/shared/tst_filesystemwatcher.h \
    $$PWD/document/model/streamiotest.h

SOURCES += \
    $$PWD/tst_core.cpp \
    $$PWD/assets/tst_assetsmanager.cpp \
    $$PWD/assets/tst_cachedpixmap.cpp \
    $$PWD/assets/tst_cachedsound.cpp \
    $$PWD/assets/tst_faceid.cpp \
    $$PWD/assets/tst_map.cpp \
    $$PWD/assets/tst_mapbundle.cpp \
    $$PWD/assets/tst_module.cpp \
    $$PWD/assets/tst_pixmap.cpp \
    $$PWD/assets/tst_sound.cpp \
    $$PWD/assets/tst_tileid.cpp \
    $$PWD/assets/tst_tileset.cpp \
    $$PWD/document/tst_document.cpp \
    $$PWD/document/graphics/tst_graphicsscene.cpp \
    $$PWD/document/graphics/tst_sceneitem.cpp \
    $$PWD/document/graphics/layeritem/tst_areaslayeritem.cpp \
    $$PWD/document/graphics/layeritem/tst_boxlayeritem.cpp \
    $$PWD/document/graphics/layeritem/tst_darealayeritem.cpp \
    $$PWD/document/graphics/layeritem/tst_layeritem.cpp \
    $$PWD/document/graphics/layeritem/tst_objectlayeritem.cpp \
    $$PWD/document/graphics/layeritem/tst_platlayeritem.cpp \
    $$PWD/document/graphics/layeritem/tst_tilelayeritem.cpp \
    $$PWD/document/graphics/layeritem/tst_walllayeritem.cpp \
    $$PWD/document/graphics/layeritem/objectitem/tst_areaitem.cpp \
    $$PWD/document/graphics/layeritem/objectitem/tst_boxitem.cpp \
    $$PWD/document/graphics/layeritem/objectitem/tst_dareaitem.cpp \
    $$PWD/document/graphics/layeritem/objectitem/tst_objectitem.cpp \
    $$PWD/document/graphics/layeritem/objectitem/tst_platitem.cpp \
    $$PWD/document/graphics/layeritem/objectitem/tst_tileitem.cpp \
    $$PWD/document/graphics/layeritem/objectitem/tst_wallitem.cpp \
    $$PWD/document/graphics/layeritem/objectitem/tileitem/tst_dooritem.cpp \
    $$PWD/document/graphics/layeritem/objectitem/tileitem/tst_randomregionitem.cpp \
    $$PWD/document/graphics/layeritem/objectitem/tileitem/tst_startpointitem.cpp \
    $$PWD/document/graphics/layeritem/objectitem/tileitem/tst_trackitem.cpp \
    $$PWD/document/graphics/tools/tst_abstracttool.cpp \
    $$PWD/document/graphics/uiitem/tst_darkmaskitem.cpp \
    $$PWD/document/graphics/uiitem/tst_hovereditem.cpp \
    $$PWD/document/graphics/uiitem/tst_mousetraceitem.cpp \
    $$PWD/document/graphics/uiitem/tst_objectareaitem.cpp \
    $$PWD/document/graphics/uiitem/tst_selecteditem.cpp \
    $$PWD/document/graphics/uiitem/tst_selecteditems.cpp \
    $$PWD/document/graphics/uiitem/tst_selectionrectangle.cpp \
    $$PWD/document/graphics/uiitem/tst_tilestampitem.cpp \
    $$PWD/document/graphics/uiitem/tst_uiitemsgroup.cpp \
    $$PWD/document/model/tst_animationsmodel.cpp \
    $$PWD/document/model/tst_areasmodel.cpp \
    $$PWD/document/model/tst_basemodel.cpp \
    $$PWD/document/model/tst_boxesmodel.cpp \
    $$PWD/document/model/tst_dareasmodel.cpp \
    $$PWD/document/model/tst_enemyfactorymodel.cpp \
    $$PWD/document/model/tst_eventsmodel.cpp \
    $$PWD/document/model/tst_platformsmodel.cpp \
    $$PWD/document/model/tst_respawnsmodel.cpp \
    $$PWD/document/model/tst_scenemodel.cpp \
    $$PWD/document/model/tst_tilelayermodel.cpp \
    $$PWD/document/model/tst_triggersmodel.cpp \
    $$PWD/document/model/tst_wallsmodel.cpp \
    $$PWD/document/model/entity/tst_animation.cpp \
    $$PWD/document/model/entity/tst_area.cpp \
    $$PWD/document/model/entity/tst_box.cpp \
    $$PWD/document/model/entity/tst_darea.cpp \
    $$PWD/document/model/entity/tst_door.cpp \
    $$PWD/document/model/entity/tst_enemy.cpp \
    $$PWD/document/model/entity/tst_enemyfactory.cpp \
    $$PWD/document/model/entity/tst_frame.cpp \
    $$PWD/document/model/entity/tst_object.cpp \
    $$PWD/document/model/entity/tst_plat.cpp \
    $$PWD/document/model/entity/tst_point.cpp \
    $$PWD/document/model/entity/tst_pointf.cpp \
    $$PWD/document/model/entity/tst_rect.cpp \
    $$PWD/document/model/entity/tst_respawn.cpp \
    $$PWD/document/model/entity/tst_startpoint.cpp \
    $$PWD/document/model/entity/tst_tile.cpp \
    $$PWD/document/model/entity/tst_tilemovemodel.cpp \
    $$PWD/document/model/entity/tst_trigger.cpp \
    $$PWD/document/model/entity/tst_wall.cpp \
    $$PWD/document/property/tst_propertyitem.cpp \
    $$PWD/document/property/tst_propertyobject.cpp \
    $$PWD/document/property/tst_propertysheet.cpp \
    $$PWD/document/undocommand/tst_objectaddcommand.cpp \
    $$PWD/document/undocommand/tst_objectundocommand.cpp \
    $$PWD/document/undocommand/tst_propertyundocommand.cpp \
    $$PWD/document/undocommand/tst_removeselectioncommand.cpp \
    $$PWD/model/tst_charactermodel.cpp \
    $$PWD/model/tst_mapsmodel.cpp \
    $$PWD/model/tst_tilesetmodel.cpp \
    $$PWD/model/tst_tilesetmodelmanager.cpp \
    $$PWD/shared/tst_filesystemwatcher.cpp \
    $$PWD/document/model/streamiotest.cpp
