#ifndef PROPERTY_H
#define PROPERTY_H

enum PropertyID
{
    PID_INVALID = 0,
    PID_NAME,
    PID_PROJECT_AUTHOR,
    PID_PROJECT_CONTACT,
    PID_PROJECT_VERSION,
    PID_PROJECT_COMMENT,
    PID_SCENE_BACKGROUND_COLOR,
    PID_SCENE_FLAG1,
    PID_SCENE_FLAG2,
    PID_SCENE_SCROLLABLE,
    PID_SCENE_START_POINT,
    PID_SCENE_FIGHT_MODE,
    PID_SCENE_NUMBER,
    PID_SCENE_SCREEN_LOCK,
    PID_SCENE_CAMERA,
    PID_SCENE_AIR_STRIKE,
    PID_SCENE_MUSIC1,
    PID_SCENE_MUSIC2,
    PID_AREA_RECT,
    PID_AREA_FLEE_DIR,
    PID_AREA_DANGER_AREA,
    PID_AREA_EDGES,
    PID_AREA_MOVE_BY,
    PID_DAREA_RECT,
    PID_DAREA_FLEE_DIR,
    PID_DAREA_TYPE,
    PID_DAREA_TARGET,
    PID_DAREA_MOVE_BY,
    PID_COUNT
};

#endif // PROPERTY_H
